language: java
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - ./gradlew check
  - ./gradlew cucumber



